<?php

namespace Alex\AnuntBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnuntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuntRepository extends EntityRepository
{
}
